jobs:
  backport:
    if: github.event.pull_request.merged
    name: Backport pull request
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Create backport pull requests
      uses: korthout/backport-action@v2
name: Backport merged pull request
on:
  repository_dispatch:
    types: trigger-ga___backport.yml
permissions:
  contents: write
  pull-requests: write
